spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plit
    username: plit
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    hibernate:
      ddl-auto: update  # (개발 중엔 update, 운영은 validate 또는 none)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # ??
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

riot:
  api:
    key: RGAPI-8e8a8e36-6299-411d-b7b5-feeffa18856b


