spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plit
    username: plit
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    hibernate:
      ddl-auto: update  # (개발 중엔 update, 운영은 validate 또는 none)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: doormouse149@gmail.com
    password: cgallkxwwlljtvsn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # ??
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

riot:
  api:
    key: RGAPI-2614a893-0fa2-48cd-975d-3810b82647c9

# 파일 업로드 경로 설정
custom:
  upload-path:
    qna: /Users/minseok/qna/uploads
    clan: /Users/minseok/dev/plit-image/



